version: '3.8'

services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    env_file:
      - ./.env
    environment:
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_MTU=${WG_MTU}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "127.0.0.1:51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
