services:
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-vpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data:/data
    environment:
      - WG_ADMIN_PASSWORD=PocketPortal2025Secure
      - WG_EXTERNAL_HOST=31.28.27.96
      - WG_PORT=51820
      - WG_VPN_CIDR=10.13.13.0/24
      - WG_DNS=1.1.1.1,1.0.0.1
      - WG_ALLOWED_IPS=0.0.0.0/0,::/0
      - WG_LOG_LEVEL=info
    ports:
      - 51820:51820/udp
      - 8000:8000/tcp
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
