version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=31.28.27.96
      - SERVERPORT=51820
      - PEERS=phone-grisha,laptop-grisha,marina-iphone
      - PEERDNS=1.1.1.1,1.0.0.1
      - ALLOWEDIPS=0.0.0.0/0,::/0
      - INTERNAL_SUBNET=10.13.13.0/24
      - LOG_CONFS=true
    volumes:
      - ./config:/config
    ports:
      - 51820:51820/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
